#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# https://github.com/lemofire/AutoDailyCP
# Lisence: MIT
# Author: 柠火
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

name: AutoDailyCP

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 9 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Download DailyCP
        run: |
          git clone https://gitee.com/Finch1/FuckDailyCP
          cp -r ./FuckDailyCP/* ./
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: DIY formdb
        run: |
          # 请根据日志提示的文件名修改此段代码
          cat>formdb/36.json<<EOF
          [{'wid': '404', 'formWid': '207', 'priority': '5', 'subject': '学生寒假离校去向统计', 'content': 'https://wecres.cpdaily.com/counselor/1018615878169362/html/a370562b4e464d5aa12f3446f13db1b7.html', 'senderUserName': '计算机科学与技术学院(白璐)', 'createTime': '2020-12-25 20:17', 'startTime': '2020-12-25 15:00', 'endTime': '2020-12-28 08:00', 'currentTime': '2020-12-26 15:45:22', 'isHandled': 1, 'isRead': 1}]
          EOF
      - name: Run program
        env:
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
          ACCOUNT: ${{ secrets.SCHOOL_ACCOUNT }}
          PASSWORD: ${{ secrets.SCHOOL_PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
        run: |
          python3 DailyCP.py ${SCHOOL_NAME} ${ACCOUNT} ${PASSWORD} ${ADDRESS}
      - name : Upload formdb
        uses: actions/upload-artifact@master
        with:
          name: formdb
          path: formdb
